version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /app/scheduler
    volumes:
      - .:/src/scheduler-for-ocf
    expose:
      - 8000
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres-dev/dev?sslmode=disable
    links:
      - postgres-dev

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: make test
    volumes:
      - .:/src/scheduler-for-ocf
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres-test/test?sslmode=disable
    links:
      - postgres-test

  postgres-dev:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dev
      - POSTGRES_PASSWORD=postgres

  postgres-test:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=postgres
